---
esphome:
  name: sound-level-meter
  platformio_options:
    board_build.f_cpu: 240000000

external_components:
  - source: github://stas-sl/esphome-sound-level-meter

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

i2s:
  bck_pin: 23
  ws_pin: 18
  din_pin: 19
  sample_rate: 48000
  bits_per_sample: 16
  bits_shift: 0
  channel: right

sound_level_meter:
  update_interval: 1s
  mic_sensitivity: -26dB
  mic_sensitivity_ref: 94dB

  sensors:
    - type: eq
      name: Leq_1s
